from django.urls import path
from .api_views import DashboardPropertyAPIView,DashboardPropertyPreviewAPIView,DashboardConsultationListAPIView,DashboardCustomerListAPIView,DashboardHomeAPIView,DashboardUpcomingAppointmentsAPIView,DashboardTodayAppointmentsAPIView,DashboardRejectAppointmentAPIView,DashboardAcceptAppointmentAPIView,DashboardAppointmentListAPIView,DashboardRollbackPropertyAPIView,DashboardPropertyVersionsAPIView,DashboardUnpublishPropertyAPIView,DashboardPublishPropertyAPIView,DashboardDeletePropertyVideoAPIView,DashboardPropertyVideoAPIView,DashboardDeletePropertyImageAPIView,DashboardPropertyImageAPIView,DashboardPropertyListAPIView,DashboardPropertyDeleteAPIView,DashboardPropertyUpdateAPIView

urlpatterns = [

    path(
        "properties/create/",
        DashboardPropertyAPIView.as_view(),
        name="dashboard-api-properties"
    ),
    path(
        "properties/",
        DashboardPropertyListAPIView.as_view(),
        name="dashboard_property_list_api"
    ),
    path(
    "properties/<int:id>/",
    DashboardPropertyUpdateAPIView.as_view(),
    name="dashboard_property_update_api"
    ),
    path(
    "properties/delete/<int:id>/",
    DashboardPropertyDeleteAPIView.as_view(),
    name="dashboard_property_delete_api"
    ),
    path(
    "properties/images/<int:id>/",
    DashboardPropertyImageAPIView.as_view(),
    name="dashboard_property_images_api"
    ),
    path(
    "properties/image/delete/<int:id>/",
    DashboardDeletePropertyImageAPIView.as_view(),
    name="dashboard_delete_property_image_api"
    ),
    path(
    "properties/videos/<int:id>/",
    DashboardPropertyVideoAPIView.as_view(),
    name="dashboard_property_videos_api"
    ),
    path(
    "properties/video/delete/<int:id>/",
    DashboardDeletePropertyVideoAPIView.as_view(),
    name="dashboard_delete_property_video_api"
    ),
    path(
    "properties/publish/<int:id>/",
    DashboardPublishPropertyAPIView.as_view(),
    name="dashboard_publish_property_api"
    ),
    path(
    "properties/unpublish/<int:id>/",
    DashboardUnpublishPropertyAPIView.as_view(),
    name="dashboard_unpublish_property_api"
    ),
    path(
    "property/<int:id>/versions/",
    DashboardPropertyVersionsAPIView.as_view(),
    name="dashboard_property_versions_api"
    ),
    path(
    "rollback/<int:version_id>/",
    DashboardRollbackPropertyAPIView.as_view(),
    name="dashboard_rollback_property_api"
    ),
    path(
    "appointments/",
    DashboardAppointmentListAPIView.as_view(),
    name="dashboard_appointment_list_api"
    ),
    path(
    "appointments/accept/<int:id>/",
    DashboardAcceptAppointmentAPIView.as_view(),
    name="dashboard_accept_appointment_api"
    ),
    path(
    "appointments/reject/<int:id>/",
    DashboardRejectAppointmentAPIView.as_view(),
    name="dashboard_reject_appointment_api"
    ),
    path(
    "appointments/today/",
    DashboardTodayAppointmentsAPIView.as_view(),
    name="dashboard_today_appointments_api"
    ),
    path(
    "appointments/upcoming/",
    DashboardUpcomingAppointmentsAPIView.as_view(),
    name="dashboard_upcoming_appointments_api"
    ),
    path(
    "dashboard/",
    DashboardHomeAPIView.as_view(),
    name="dashboard_home_api"
    ),
    path(
    "customers/",
    DashboardCustomerListAPIView.as_view(),
    name="dashboard_customer_list_api"
    ),
    path(
    "consultations/",
    DashboardConsultationListAPIView.as_view(),
    name="dashboard_consultation_list_api"
    ),
    path(
    "properties/preview/<int:id>/",
    DashboardPropertyPreviewAPIView.as_view(),
    name="dashboard_property_preview_api",
    ),
    

]