# Generated by Django 6.0.5 on 2026-06-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requirements', models.TextField()),
                ('status', models.CharField(default='New Lead', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
