# Generated by Django 5.0.6 on 2026-06-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_broker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.broker'),
        ),
        migrations.AddField(
            model_name='consultationlead',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.broker'),
        ),
    ]
