# Generated by Django 5.0.6 on 2026-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_appointment_broker_consultationlead_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationlead',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationlead',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationlead',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
