# Generated by Django 6.0.5 on 2026-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_consultationlead_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationlead',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationlead',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='consultationlead',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.URLField(max_length=500),
        ),
    ]
