# Generated by Django 6.0.5 on 2026-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_consultationlead_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyversion',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
