# Generated by Django 5.0.6 on 2026-06-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_publish_status_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('publish_status', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area_sqft', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='properties.property')),
            ],
        ),
    ]
