# Generated by Django 5.0.6 on 2026-06-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_consultationlead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.broker'),
        ),
    ]
